config/routes.rb
Rails.application.routes.draw do
  resources :characters do
    resources :ukes, only: [:create, :destroy]
    resources :semes, only: [:create, :destroy]
  end
  root to: 'top#top'
  get "modal" => "top#modal"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  validates :name, presence: true
  has_many :ukes, dependent: :destroy
  has_many :semes, dependent: :destroy
end

app/models/seme.rb
class Seme < ApplicationRecord
  validates :character_id, { presence: true }

  belongs_to :character
end

app/models/uke.rb
class Uke < ApplicationRecord
  validates :character_id, { presence: true }

  belongs_to :character
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all.order(created_at: :DESC).page(params[:page]).per(7)
  end

  def edit
    @character = Character.find(params[:id])
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)
    if @character.save
      redirect_to characters_url, notice: "「#{@character.name}」を登録しました！"
    else
      render :new
    end
  end

  def destroy
    character = Character.find(params[:id])
    character.destroy
    redirect_to characters_url, notice: "「#{character.name}」を削除しました！"
  end

  def update
    character = Character.find(params[:id])
    binding.irb
    character.update!(character_params)
    redirect_to characters_url, notice: "「#{character.name}」を更新しました！"
  end

  private

  def character_params
    params.require(:character).permit(:name)
  end
end

app/controllers/semes_controller.rb
class SemesController < ApplicationController
  def create
    @seme = Seme.create(character_id: params[:character_id])
    redirect_to characters_url
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def top; end
end

app/controllers/ukes_controller.rb
class UkesController < ApplicationController
  def create
    @uke = Uke.create(character_id: params[:character_id])
    redirect_to characters_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/semes_helper.rb
module SemesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/ukes_helper.rb
module UkesHelper
end

app/views/characters/_form.html.slim
= form_with model: character, local: true do |f|
  .form-group.mx-5
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'character_name'
  = f.submit nil, class: 'btn btn-outline-secondary'

app/views/characters/edit.html.slim
h1 キャラクターの編集


.nav.justify-content-end
  = link_to '一覧', characters_path, class: 'nav-link'

= render partial: 'form', locals: { character: @character }

app/views/characters/index.html.slim
  .mb-2
    = link_to '　　　キャラクターを登録する　　　', new_character_path, class: 'btn btn-outline-secondary'
    .mb-3
    = link_to '使い方', modal_path, remote: true, class: "btn btn-outline-secondary"
  #user-modal.modal.fade aria-hidden="true" role="dialog" tabindex="-1" 

  table.table.table-hover.col-8.mx-auto
    thead.thead-default
      tr 
        th= Character.human_attribute_name(:name)
        th 受け数
        th 攻め数
        th
      tbody 
        - @characters.each do |character|
          tr 
            td= character.name
            td= link_to character_ukes_url(character), method: :post do
              = character.ukes.count
            td= link_to character_semes_url(character), method: :post do
              = character.semes.count
            td 
              =link_to "http://twitter.com/share?url=#{request.url}/&text=#{character.name}には受けが#{character.ukes.count}票、攻めが#{character.semes.count}票入ってるよ！BLvoteで投票してみよう！&hashtags=BLvote", title: 'Twitter', target: '_blank' do 
                i.fab.fa-twitter
  = paginate @characters

app/views/characters/new.html.slim
h1 キャラクターの登録

.nav.justify-content-end
  = link_to '一覧', characters_path, class: 'nav-link'

= render partial: 'form', locals: { character: @character }

app/views/layouts/application.html.slim
doctype html
html
  head
    meta name="twitter:card" content="summary"
    meta name="twitter:site" content="@ayakocareer"
    meta property="og:url" content="https://blvote.herokuapp.com/"
    meta property="og:title" content="BL VOTE"
    meta property="og:description" content="あのキャラクターは受け？攻め？さぁ、投票してみよう！"
    meta property="og:image" content= asset_url('logo.png')
    title
      | BLVote
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand 
      = link_to characters_path do
        = image_tag('/header.png' , size: "110x40")
    .container.p-3
      - if flash.notice.present?
        .alert.alert-success= flash.notice
    .fixed-bottom.navbar.navbar-expand-md.navbar-light.bg-light.p-4.justify-content-end
        i.fas.fa-copyright 2021 ayako　
        = link_to 'https://twitter.com/ayakocareer' do 
          i.fab.fa-twitter
    = yield

app/views/layouts/top.html.slim
doctype html
html
  head
    meta name="twitter:card" content="summary"
    meta name="twitter:site" content="@ayakocareer"
    meta property="og:url" content="https://blvote.herokuapp.com/"
    meta property="og:title" content="BL VOTE"
    meta property="og:description" content="あのキャラクターは受け？攻め？さぁ、投票してみよう！"
    meta property="og:image" content= asset_url('logo.png')

    title
      | BLVote
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
    = yield

app/views/top/_modal.html.slim
.modal-dialog.modal-dialog-centered. role="document" 
  .modal-content
    .modal-body
      | ①投票したいキャラクターを登録します
      br
      | ②キャラクターを登録したら、受け攻め投票をします！
      br
      | ③受け攻め投票は一人何票でも可能です！

app/views/top/modal.html.slim
.modal-dialog role="document" 
  .modal-content
    | 頼むから出て

app/views/top/modal.js.erb
$("#user-modal").html("<%= escape_javascript(render 'modal') %>")
$("#user-modal").modal("show")

app/views/top/top.html.slim
br
br
img src= "top.png"


p = link_to '大丈夫なので入室する', characters_url, class: 'btn btn-outline-secondary'
p = link_to 'ボーイズラブとは何か知りたい', 'https://ja.wikipedia.org/wiki/%E3%83%9C%E3%83%BC%E3%82%A4%E3%82%BA%E3%83%A9%E3%83%96', class: 'btn btn-outline-info'